%YAML:1.0
---
#PathRec: "D:\\PreciseLocalization\\Dataset\\VLdataset_MultiModal\\T3-Lib\\reference\\"
#PathTest: "D:\\PreciseLocalization\\Dataset\\VLdataset_MultiModal\\T3-Lib\\query\\"
#PathRec: "D:\\PreciseLocalization\\Dataset\\VLdataset_MultiModal\\T3-Gate\\reference\\"
#PathTest: "D:\\PreciseLocalization\\Dataset\\VLdataset_MultiModal\\T3-Gate\\query\\"
PathRec: "E:\\PreciseLocalization\\Dataset\\VLdataset_MultiModal\\T3-T3\\reference\\"
PathTest: "E:\\PreciseLocalization\\Dataset\\VLdataset_MultiModal\\T3-T3\\query\\"
#PathRec: "D:\\PreciseLocalization\\Dataset\\VLdataset_MultiModal\\Gate-T3\\reference\\"
#PathTest: "D:\\PreciseLocalization\\Dataset\\VLdataset_MultiModal\\Gate-T3\\query\\"
BoW_CodeBook: "orbvoc.dbow3"
# ImgType - whether to use the specific modality
ColorImg: 1 # color is essential for place recognition
DepthImg: 1
InfraredImg: 1
databaseImgSize: [ 320, 240 ]
queryImgSize: [ 320, 240 ]
# whether to use GPS data
GPS: 1
# Descriptor: 
GIST: 1
ORB-BoW: 1
LDB: 1
# whether to use color images
Color: 1
# Choose the running mode of OpenMPR: 
# 1 - run visual localziation
# 2 - locate only with GPS
# 3 - GASearch
# 4 - SweepSearch
Mode: 2
